customhost = "projectcc-database.c9uj0gns7dba.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "qwertyuiop"
customdb = "users"
custombucket = "projectcc"
customregion = "us-east-1"
customtopic = "arn:aws:sns:us-east-1:901876227683:projectcc"